### ISSUE TITLE
peaks and spectra have a scans argument that is not documented

### ISSUE THREAD

**Issue by sgibb** [sneumann/mzR#134]
`peaks` and `spectra` have a `scans` argument that is not documented in the *Usage* section. In the *Arguments*/*Details* section you find the hint that it is supported.

https://github.com/sneumann/mzR/blob/60e3945ef3ba207274ef1daea26e3c4219361e19/man/peaks.Rd#L48-L50

Could it be added to the *Usage* section as well?

**Comment by jotsetung** [comment]
Nope, we can not add scans to the usage section for `spectra` and `peaks`, since the argument is not present in its generic: `setGeneric("peaks", function(object, ...) standardGeneric("peaks"))` defined in `ProtGenerics`

`header` on the other hand (defined in `mzR`) has: `setGeneric("header", function(object, scans, ...) standardGeneric("header"))`

**Comment by sgibb** [comment]
I don't want to be nitpicking but `\S4method{peaks}{mzRpwiz}(object, scans)` works. In fact in the current *usage* section just the generic is documented (that moved to `ProtGenerics`) and the S4 methods are just aliases which the user never sees. I can understand that multiple `peaks` entries `\S4method{peaks}{mzRramp}(object, scans)`, `\S4method{peaks}{mzRpwiz}(object, scans)`, ... are not pretty and can mislead the user too.

**Comment by lgatto** [comment]
I think it would be good to be more explicit. We do mention it in `scans` in the arguments section, but that is a bit cryptic; there isn't even a useful example at the end.

@sgibb - I am happy to merge a PR with the `\S4method{peaks}{mzRpwiz}(object, scans)` and an updated example if you have time, otherwise I'll do it.

**Comment by lgatto** [comment]
Has this been addressed?

**Comment by jotsetung** [comment]
I didn't.
