### ISSUE TITLE
header() error 

### ISSUE THREAD

**Issue by magnuspalmblad** [sneumann/mzR#197]
I get the following error when trying to read the header info from an mzML file generated with msconvert (3.0.19120 and 3.0.11537) using the mzR header() function:

Error in object@backend$getAllScanHeaderInfo() : 
  [read_file_header()] Unable to open file 2018-10-18_HeLa_OTOT.mzML (invalid permission or file locked)

The openMSfile(), instrumentInfo() and tic() functions work without error. I get the same error on any mzML file. Any ideas?

I run 64-bit R 3.5.2 under Windows 7.

**Comment by lgatto** [comment]
I don't know about the issue, unfortunately - I have never seen the *invalid permission of file locked* message. Is the data local, or do you access it over the network?

By the way, you should look in `MSnbase` and the `readMSData(..., mode = "onDisk")` function rather than using the raw mzR interface. Using the former will get you the fast on disk access from mzR with a well defined interface and support for multiple files. Note that this is unlikely to fix you issue, unfortunately, but will make you life easier.

**Comment by magnuspalmblad** [comment]
Thanks for the hint! Moving over to MSnbase now. Should give me more control, and hopefully help diagnose/find a workaround for these issues. The file is local, and seems to open fine with readMSData().
