### ISSUE TITLE
mzR timeouts on Windows

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#21]
Recording a email exchange with @dtenenba re `mzR`, that often fails to install on windows within 40 minutes.

The suggestion by @thirdwing and @sneumann was to ship `libpwiz.a` for Windows in the package.

Has anyone time to tackle this at some point?

**Comment by thirdwing** [comment]
Just try to compile the ``libpwiz.a``. Very easy work, however, it is more 80MB.

**Comment by dtenenba** [comment]
So the current .zip file is 10MB and adding libpwiz.a would make it 90MB?

Is that because the static build would include things that are not normally included in the mzR dll? Is there any way the source could be pruned?

Anyway, if this is not too difficult I'd like to test it, would it be possible to create a github branch that uses the static libpwiz on windows? I would like to see how much of a difference it makes in install time then we can figure out how to handle the size tradeoff.

Thanks.

**Comment by thirdwing** [comment]
Give me a little time.

I made a mistake. We don't need the whole pwiz library, we just need a part
of it.

On Fri, Feb 20, 2015 at 8:23 PM, dtenenba <notifications@github.com> wrote:

> So the current .zip file is 10MB and adding libpwiz.a would make it 90MB?
>
> Is that because the static build would include things that are not
> normally included in the mzR dll? Is there any way the source could be
> pruned?
>
> Anyway, if this is not too difficult I'd like to test it, would it be
> possible to create a github branch that uses the static libpwiz on windows?
> I would like to see how much of a difference it makes in install time then
> we can figure out how to handle the size tradeoff.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sneumann/mzR/issues/21#issuecomment-75348046>.
>



-- 
Qiang Kou
qkou@umail.iu.edu
School of Informatics and Computing, Indiana University

**Comment by lgatto** [comment]
I created the `staticwin` branch for testing.

**Comment by thirdwing** [comment]
Hi, @lgatto , can you add me as a collaborator of this project? Then I can push to the branch.

**Comment by lgatto** [comment]
> can you add me as a collaborator of this project
@thirdwing No, I'm afraid not; I don't have rights to do so.

**Comment by thirdwing** [comment]
@dtenenba @lgatto  please try my repo https://github.com/thirdwing/mzR-1

**Comment by lgatto** [comment]
Checks fine on my linux. 

@thirdwing could you document in this issue or directly in ` src/Makevars.win` how `src/win/i386/libpwiz.a` and `src/win/x64/libpwiz.a` were generated.

**Comment by sneumann** [comment]
Done.

**Comment by sneumann** [comment]
Sorry, "done" was ambiguous, and here referring to adding KK to the repo.

**Comment by thirdwing** [comment]
@lgatto  Of course I will provide how to compile ``libpwiz``, we need to make sure it can pass ``R CMD check`` first.

**Comment by thirdwing** [comment]
The source code and ``Makefile`` to build ``libpwiz.a`` is at https://github.com/thirdwing/libpwiz

**Comment by sneumann** [comment]
Great. Can we put the Makefile as e.g. Makefile.createlibpwiz into mzR/src itself, 
so that this can be used to recreate libpwiz.a from within mzR source package ? 
Then there is no danger to have it out of sync

**Comment by lgatto** [comment]
> Can we put the Makefile as e.g. Makefile.createlibpwiz into mzR/src itself, so that this can be used to recreate libpwiz.a from within mzR source package? 

I was about to ask the same questions.

**Comment by thirdwing** [comment]
I have just send a PR. If it can pass the Bioconductor check, I will merge everything related into the ``mzR`` package.

**Comment by lgatto** [comment]
Let's keep the issue open so we don't forget to add the `libpwiz.a` building instructions.

**Comment by sneumann** [comment]
Right Laurent. I just checked on my Windows installation, 
and can't reproduce the build failure http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/moscato2-install.html 

````
g++ -m32 -shared -s -static-libgcc -o mzR.dll tmp.def cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o R_init_mzR.o rampR.o -L./win//i386 -lws2_32 -lnetcdf -lpwiz -LE:/biocbld/bbs-3.1-bioc/R/library/zlibbioc/libs/i386 -lzlib1bioc -Ld:/RCompile/r-compiling/local/local300/lib/i386 -Ld:/RCompile/r-compiling/local/local300/lib -LE:/biocbld/BBS-3˜1.1-B/R/bin/i386 -lR
c:/rtools32/gcc-4.6.3/bin/../lib/gcc/i686-w64-mingw32/4.6.3/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lpwiz
````

**Comment by lgatto** [comment]
@dtenenba any idea?

**Comment by dtenenba** [comment]
None.

**Comment by dtenenba** [comment]
@sneumann can you post the sessionInfo() on the machine you are trying to built it on and the command you are using? Mine is 

```
> sessionInfo()
R Under development (unstable) (2015-02-18 r67837)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2008 R2 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C
[5] LC_TIME=English_United States.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base
```

```
R.exe CMD INSTALL --merge-multiarch mzR_2.1.10.tar.gz && rm mzR_2.1.10.tar.gz
```

**Comment by dtenenba** [comment]
Also, if you run 

```
R.exe CMD INSTALL --merge-multiarch --build mzR_2.1.10.tar.gz && rm mzR_2.1.10.tar.gz
```

How large is the resulting zip file?

**Comment by sneumann** [comment]
Hi Dan,

If I run R.exe CMD INSTALL --merge-multiarch --build mzR_2.1.10.tar.gz
the resulting ZIP is 3.997.599 mzR_2.1.10.zip. I can try to find a 64bit build environment
later this week, but on the 64bit BioC machines it is already the 32bit part that breaks,
which works over here.

Yours,
Steffen

my > sessionInfo() is:

R version 3.1.0 (2014-04-10)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C
[5] LC_TIME=German_Germany.1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] mzR_2.1.10  Rcpp_0.11.3

loaded via a namespace (and not attached):
[1] Biobase_2.25.1      BiocGenerics_0.11.5 codetools_0.2-8
[4] parallel_3.1.0      zlibbioc_1.12.0

**Comment by dtenenba** [comment]
It looks like the problem is the git svn bridge. libpwiz.a does not exist in svn, only git. I will work on resolving this.

**Comment by dtenenba** [comment]
Those files are in svn now. Sorry about the glitch.

**Comment by thirdwing** [comment]
Let's hope it can pass all the testing. Then I will merge how to build ``libpwiz.a`` into this repo.

**Comment by dtenenba** [comment]
It works! Thanks everyone!
Dan

**Comment by lgatto** [comment]
Great!

**Comment by thirdwing** [comment]
The ``Makefile`` to build ``libpwiz`` is merged into https://github.com/sneumann/mzR/tree/libpwiz

**Comment by lgatto** [comment]
Thanks, KK. Closing the issue now.

**Comment by dtenenba** [comment]
I hate to mention it but after updating R-devel on the build machines yesterday, mzR is timing out during INSTALL again on Windows. http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/moscato2-install.html

**Comment by thirdwing** [comment]
OK. I will look into it.

**Comment by sneumann** [comment]
Hi,

with the current gcc492 toolchain both the recent build errors 
and the timeouts are gone.

just for the record, Windows build time is around 1400secs, 
which is remarkable since the other arches compile waay more 
source files.

Anyway, mzR is looking good for the coming release, afaics.
Thanks everyone for the efforts,

Yours,
Steffen



On Di, 2015-03-10 at 15:09 -0700, Qiang Kou (KK) wrote:
> OK. I will look into it.
> On Mar 10, 2015 6:08 PM, "dtenenba" <notifications@github.com> wrote:
> 
> > I hate to mention it but after updating R-devel on the build
> machines
> > yesterday, mzR is timing out during INSTALL again on Windows.
> >
> http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/moscato2-install.html
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sneumann/mzR/issues/21#issuecomment-78159271>.
> >
> 
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> 


-- 
IPB Halle                    AG Massenspektrometrie & Bioinformatik
Dr. Steffen Neumann          http://www.IPB-Halle.DE
Weinberg 3                   http://msbi.bic-gh.de
06120 Halle                  Tel. +49 (0) 345 5582 - 1470
                                  +49 (0) 345 5582 - 0
sneumann(at)IPB-Halle.DE     Fax. +49 (0) 345 5582 - 1409

**Comment by sneumann** [comment]
We are back on a timeout after the build system reverted to the old toolchain.

@dtenenba : I request an exemption for mzR to the timeout rule, as the problem 
will go away when the gcc492 toolchain will be used again. I somehow suspect 
that the linking stage takes so long, since we eliminated the majority of compilations 
by providing the prebuilt pwiz library. Or, we eliminated all but the most time consuming compiles.
If it is not the linking, possibly removing -O2 might save some time. Yours, Steffen

**Comment by lgatto** [comment]
`mzR` is not the only package that suffers from timeouts on Windows. [`MSnbase`](http://bioconductor.org/checkResults/3.1/bioc-LATEST/MSnbase/moscato2-checksrc.html), [`rpx`](http://bioconductor.org/checkResults/3.1/bioc-LATEST/rpx/petty-buildsrc.html) has the same problem (which I am unable to reproduce locally), and none has C/C++ code (although this has just changed for the former) and do not take as much time as `mzR` to build/check.

**Comment by dtenenba** [comment]
There might be an issue with the build system. If you look at http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/moscato2-install.html and scroll to the bottom, it looks like the installation process completes, yet it is still marked as a TIMEOUT. 
And packages that depend on mzR did not fail, which they typically do when mzR does not really install. 

@lgatto : curiously all these packages with timeouts have something to do with you. ;-) Is there some other common factor?

**Comment by lgatto** [comment]
@dtenenba is it really only my packages?!?!

**Comment by dtenenba** [comment]
@lgatto no. On windows rpx does not time out, there are 3 others besides mzR and MSnbase. rpx is timing out on Snow Leopard. I'll take a look at that. @sneumann I'm not sure how straightforward it would be to add an exemption to the build system. I'll have to look into it.

**Comment by lgatto** [comment]
@dtenenba yes, indeed... whenever I see a timeout, I blame Windows ;-)

**Comment by sneumann** [comment]
@dtenenba is there any way to estimate which command is consuming the majority of the build time ?

We had the situation with "looks-like-it-actually-completed-in-time" before:
````
On Di, 2015-02-17 at 11:43 -0800, Dan Tenenbaum wrote:
> Today we are back to a "true" timeout where it does not get to "DONE". (I am looking into that).
[...]
> ----- Original Message -----
> > From: "Steffen Neumann" <sneumann@ipb-halle.de>
> > To: "Dan Tenenbaum" <dtenenba@fredhutch.org>
[...]
> > The mzR moscato2 windows INSTALL log includes:
[...]
> > * DONE (mzR)
[...]
> > So to me it looks as if everything was finished, and that moscato2
> > didn't realise
> > everything was finished. Could please try to find out what is going
> > on
> > with moscato2 during an actual timeout'ing build ?
````
Yours,
Steffen

**Comment by dtenenba** [comment]
Just by running the install command manually and watching. 
Sometimes when you install a package it pauses after it says * DONE (mzR) before returning to the command prompt. If 2400 seconds rolls around at that moment then we'd see what we saw today, the build report marked as a TIMEOUT but mzR successfully installed.

**Comment by sneumann** [comment]
Just for the record, we're down to 1500secs on todays build. Closing for the next few days ...

**Comment by sneumann** [comment]
Back to 2500sec timeout.

**Comment by sneumann** [comment]
Given that mzR INSTALLs on other machines in 550/650/400 seconds, 
and that mzR compiled on Windows in 1500secs on 25.03.2015
and even "only" 1400secs on 16.03.2015 with the gcc492 toolchain, 
I don't see a chance how we can further optimize mzR 
beyond the inclusion of the precompiled libpwiz.a 
which we did in february, and which didn't really address 
the actual problem:

It seems that indeed the linking step is known to be slow in mingw:
http://stackoverflow.com/questions/929495/why-is-mingw-very-slow
http://sciviz.cct.lsu.edu/projects/vish/vish/ming.html

The following post indicates that moving to dynamic linking 
with libpwid.dll would be even slower:
https://ghc.haskell.org/trac/ghc/ticket/8229

An optimisation could be the ld.exe from U++ project 
on the build machines:
http://mingw-users.narkive.com/bJ420BBf/ot-ann-uld-uar-ld-ar-replacements
Caveat: I have no experience with their ld and ar, 
and http://iweb.dl.sourceforge.net/project/upp/uldar/1.0.15/ 
is over ten years old. Which, OTOH, could mean it is rock solid 
and did not need any changes since then.

**Comment by sneumann** [comment]
Response from Dan:


I installed this on moscato2. Can mzR be changed so that it uses this ld and ar? I set an environment variable ULDAR to point to the directory where this ld and ar are installed so you can refer to it in your Makevars/configure scripts/etc. 

If you like you can try building it with the single package builder, or just change it and see how it does during the nightly builds.

Thanks,
Dan

**Comment by sneumann** [comment]
I will try to update CFLAGS to  -Wl,--dynamic-linker=<path to linker>
as mentioned in http://www.unix.com/programming/122374-gcc-choose-my-own-linker.html

**Comment by sneumann** [comment]
we have been below 2000s for a few days now.

**Comment by sneumann** [comment]
Down to 1000s on windows. I will close for now.

**Comment by sneumann** [comment]
From Dan:
Please set the environment variable ULDAR to point to this ld and ar as I requested in 
https://github.com/sneumann/mzR/issues/21#issuecomment-87802019

**Comment by thirdwing** [comment]
We have the timeout problem again.

http://bioconductor.org/checkResults/release/bioc-LATEST/mzR/moscato1-install.html

**Comment by sneumann** [comment]
Yes,  I am a bit clueless here.

I added to use the ULDAR linker,
A while ago,
Which is supposedly faster.

My only idea would be to try
To compile the static library
Optimised for quick linking,
But I would not know how.

The other architectures finish
In under ten minutes /including/
The compilation....

**Comment by dtenenba** [comment]
Note that @thirdwing is referring to the release builds; was the release branch updated to use the ULDAR linker? Also, is there any way to tell from the build output whether the package is **actually** using that linker?

**Comment by sneumann** [comment]
Ah, right Dan. actually, the issue is present on both release *and* devel.
Release is using the standard LD while devel uses -Wl,--dynamic-linker=c:/uldar/ld.exe

Both finish INSTALL with "DONE (mzR)" and still time out.

Release finished BUILD OK, while on devel also BUILD times out, even though its 
output looks identical to release end they end with:

* building 'mzR_2.4.0.tar.gz'
* building 'mzR_2.5.3.tar.gz'

**Comment by dtenenba** [comment]
@sneumann I will look into that.

**Comment by dtenenba** [comment]
@sneumann @thirdwing @lgatto 

Sorry to bring this up again, but we are again planning to switch to the gcc-4.9.3-based toolchain for the release of R-3.3.0. So I need to rebuild libpwiz.a. It seems the way to build it is:

```
cd src
make -f Makefile.libpwiz
```

That produces libpwiz.a. But how do I know if that is for i386 or x64, and whichever one it is, how do I build the other one?

Thanks.

**Comment by thirdwing** [comment]
Hi, @dtenenba 

I don't have the time to test new toolchain. I spent some time in packing the toolchain with other people.

As I remember, there is no cross-compiling option in the new one. Let me have a check.

**Comment by dtenenba** [comment]
@thirdwing I just need to know how to build libpwiz.a for both i386 and x64, on windows.

**Comment by thirdwing** [comment]
Sorry that I used the wrong word. I mean the multiarch support.

In the GCC4.6.3 toolchain, if you add `-m64` flag, then it will produce the lib for x64. `-m32` is for i386.

**Comment by dtenenba** [comment]
@thirdwing Can you specify exactly where I should use the -m64  and -m32 flags in the Makefile? What changes should i make to it for each sub-architecture? I apologize for my ignorance but I don't know how to do this.

I did try to build both libraries using the following technique:

```
cd mzR/src
# remove C:/Rtools/mingw_64/bin from the PATH'
make -f Makefile.libpwiz clean
make -f Makefile.libpwiz
cp libpwiz.a win/i386/
# add C:/Rtools/mingw_64/bin, remove C:/Rtools/mingw_32/bin from PATH
make -f Makefile.libpwiz clean
make -f Makefile.libpwiz
cp libpwiz.a win/x64/
```

Then I tried to install mzR as follows:

```
cd ../..
R CMD build --no-build-vignettes mzR
R CMD INSTALL --merge-multiarch mzR_2.5.5.tar.gz
```

The i386 portion of the install was successful but the x64 portion failed as follows:

```
...
C:/Rtools/mingw_64/bin/g++  -I"e:/biocbld/BBS-3~1.3-B/R/include" -DNDEBUG -D_LARGEFILE_SOU
RCE -I./boost_aux/ -I./boost -I. -DHAVE_PWIZ_MZML_LIB  -DWITHOUT_MZ5 -fpermissive -DWINDOW
S_NATIVE     -I"e:/biocbld/bbs-3.3-bioc/R/library/Rcpp/include" -I"e:/biocbld/bbs-3.3-bioc
/R/library/zlibbioc/include" -I"c:/local323/include" -c rampR.cpp -o rampR.o
C:/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o mzR.dll tmp.def cramp.o ramp_base6
4.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o R
cppIdentModule.o R_init_mzR.o rampR.o -Wl,--dynamic-linker=c:/uldar/ld.exe -L./win//x64 -l
ws2_32 -lnetcdf -lpwiz -Lc:/local323/lib/x64 -Lc:/local323/lib -Le:/biocbld/BBS-3~1.3-B/R/
bin/x64 -lR
R_init_mzR.o:R_init_mzR.c:(.text+0x0): multiple definition of `strncasecmp'
rnetCDF.o:rnetCDF.c:(.text+0x0): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0x10): multiple definition of `strcasecmp'
rnetCDF.o:rnetCDF.c:(.text+0x10): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0x20): multiple definition of `_findfirst64i32'
rnetCDF.o:rnetCDF.c:(.text+0x20): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0xa0): multiple definition of `_findnext64i32'
rnetCDF.o:rnetCDF.c:(.text+0xa0): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0x120): multiple definition of `_fstat64i32'
rnetCDF.o:rnetCDF.c:(.text+0x120): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0x1b0): multiple definition of `_stat64i32'
rnetCDF.o:rnetCDF.c:(.text+0x1b0): first defined here
R_init_mzR.o:R_init_mzR.c:(.text+0x240): multiple definition of `fstat'
rnetCDF.o:rnetCDF.c:(.text+0x240): first defined here
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'mzR'
                                             
```

**Comment by thirdwing** [comment]
Using the old toolchain, I just add `-m32` into this line https://github.com/sneumann/mzR/blob/master/src/Makefile.libpwiz#L4

The multiple definition of `strncasecmp` is more like one problem in the toolchain.

**Comment by dtenenba** [comment]
@thirdwing  OK. We will need to solve this as soon as possible. The package will need to build with the new toolchain as that is what R-3.3.0 will use.

If you can get it to build with the new toolchain that would be great. 
[Here](https://github.com/Bioconductor/Bioconductor/blob/master/documentation/new-toolchain-setup.md) are some instructions for setting up & developing with the new toolchain.

If you can get mzR to install with the new toolchain that would be great.

Or if you have an idea for something for me to try regarding the above error, let me know and I will try it.

That error seems to suggest the problem is in libnetcdf.a;. However, my understanding is that netcdf is written in C, so there should be no incompatibility. My understanding is that only the use of C++ in a system dependency causes binary incompatibility. 

I just committed the new libpwiz libraries to devel so you should not need to build them again.
(Though I may have built them wrong).

Tagging @lgatto @sneumann just so you are all aware that compatibility with the new toolchain is going to be urgent. Hopefully tomorrow's build report will reflect the first build that uses it, I will send an announcement to bioc-devel about it.

**Comment by thirdwing** [comment]
I am afraid I may not have time to fix this until the weekend. But I will try.

**Comment by dtenenba** [comment]
I could be wrong that the problem is with libnetcdf.a. I thought it was because of the `netCDF` in this output:

```
R_init_mzR.o:R_init_mzR.c:(.text+0x0): multiple definition of `strncasecmp'
rnetCDF.o:rnetCDF.c:(.text+0x0): first defined here
```

However, I renamed `src/win/x64libnetcdf.a` to `libnetcdf.a.bak` and got exactly the same error, so this means it could be a problem at the header level or it may have nothing to do with the library. This is yet another reason why it would be good for a maintainer to look at this.
