### ISSUE TITLE
raw data reading

### ISSUE THREAD

**Issue by hh1985** [sneumann/mzR#31]
Just curious, can mzR be extended to support the reading of vendor raw files?

**Comment by thomasp85** [comment]
In theory yes, as protowizard supports it. But practically probably no as it would only work on Windows but worse, including vendor libraries would impose additional license agreements to mzR

**Comment by thirdwing** [comment]
Agree with @thomasp85 .

**Comment by hh1985** [comment]
Thank you all for the reply!  I was thinking about ways like letting the user install proteowizard program first, and letting R package to access the installed dll, but it seems difficult to achieve in R:(

**Comment by lgatto** [comment]
> I was thinking about ways like letting the user install proteowizard program first, and letting R package to access the installed dll, but it seems difficult to achieve in R :(

That would actually be quite easy using `system()` and feeding it whatever system command you want to be executed.

**Comment by sneumann** [comment]
Hi hh1985,

as Laurent said, it is possible
And indeed I have been hoping for many years for some brave windows hacker to try this.

We will not be able to have this in the
Standard Bioconductor build, but as a first step you could try to hack this and provide a README.vendor<http://README.vendor> which explains the procedure.

You could try to put your own
mzR.dll<http://mzR.dll> target into the mzR/src/Makevars.win<http://Makevars.win>
Which does not link against the prebuilt
Non-vendor pwiz library we ship in mzR,
But instead the vendor-enabled one
That is system installed as you correctly suggested.

I dont know anything about developing on Windows, but I guess the biggest hurdles is to tell it where to find its libraries. The other issue could be mixing compilers,  since R uses mingw for R and package compilation ,
While pwiz uses something else.

Yours Steffen

---
I blame Android for the brevity and typos

**Comment by hh1985** [comment]
Hi Steffen and Laurent,

Thanks for the suggestions.
I used to compile proteowizard into libraries (.lib and .dll), and let my
test c++ program to extract information directly from vendor raw files. It
would be much more convenient if everything can be finished through R! This
case is different, but I will do some googling based on your information,
and see if there's any way:)

Regards,

-Han

**Comment by sneumann** [comment]
Back on a "real" keyboard :-)

As you see here: http://bioconductor.org/checkResults/devel/bioc-LATEST/mzR/zin2-buildsrc.html
the final linking for x64 is done on windows with 
````g++ -m64 -shared -s -static-libgcc -o mzR.dll tmp.def cramp.o ramp_base64.o ramp.o RcppRamp.o RcppRampModule.o rnetCDF.o RcppPwiz.o RcppPwizModule.o RcppIdent.o RcppIdentModule.o R_init_mzR.o rampR.o -L./win//x64 -lws2_32 -lnetcdf -lpwiz -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LE:/biocbld/BBS-3˜1.3-B/R/bin/x64 -lR ````

and you need to find a way that ````-lpwiz```` actually comes from your full-blown pwiz installation.
The laziest approach is to first install mzR normally from source, and then re-create mzR.dll with the linked full libpwiz.dll, and copy the resulting mzR.dll over the existing mzR.dll in your R library/mzR/ installation. Caveat, I am not entirely sure how R handles the dual-architecture i386/x64 installations,
there you also need to match the architecture of the installed pwiz.

Yours,
Steffen

**Comment by hh1985** [comment]
Hi Steffen,

Thanks a lot!  I can get a lot of .lib files
ibpwiz_data_msdata.lib
libpwiz_data_msdata_mz5.lib
libpwiz_data_msdata_version.lib
libpwiz_utility_minimxml.lib
libpwiz_version.lib
libhdf5.lib
libhdf5pp.lib
libpwiz_data_vendor_readers.lib
libpwiz_data_common.lib
libpwiz_tools_common.lib
libpwiz_analysis_common.lib
libpwiz_analysis_passive.lib
libpwiz_analysis_passive_core.lib
libpwiz_analysis_spectrum_processing.lib
...

Their range can be tracked through the corresponding jamfile.jam files. As
suggested in http://www.mingw.org/wiki/MSVC_and_MinGW_DLLs, I will try to
link the lib using gcc. But which one is the "libpwiz" you mentioned? I
think I can arbitrarily make one that combines msdata and vendor_readers if
necessary.

And, Merry Christmas Eve!

-Han

**Comment by sneumann** [comment]
Libpqiz.dll<http://Libpqiz.dll> shows my ignorance how development on Windows works...

---
I blame Android for the brevity and typos

**Comment by hh1985** [comment]
It seems we're getting close!  I successfully used a hello world test program (e.g. main.exe from g++) to read thermo raw files. It requires a lot of tricks to squeeze the dll file from proteowizard project. In order to get a fully functional dll, I have to write a whole C layer for all functions.

![capture](https://cloud.githubusercontent.com/assets/7053284/12005016/0372c20c-ab56-11e5-9fed-fe195ba7d28f.PNG)

**Comment by sneumann** [comment]
Hi, so you decouple the mingw compiled mzR.dll<http://mzR.dll> from the (presumably) visual studio compiled Libpwiz.dll<http://Libpwiz.dll> via a layer of c code?  I don't think that is maintainable. Or did you use your main.exe<http://main.exe> to
Test how to link against libpwiz?

What breaks if you just use
The g++ -shared...  Line I sent earlier?
And use -L to point to where pool pwiz
Was compiled, so that the full vendor libs enabled msdata is used?
Yours Steffen

---
I blame Android for the brevity and typos

**Comment by hh1985** [comment]
Hi Steffen,

I was not even there. I wrote a simple C wrapper for the pwiz part, and get
the dll. Only two functions there, one is for reading, and the other for
writing.

The name mangling is a big issue for g++ to recognized dll from msvc. The
only practical way I've found is to add a C layer. But the namespace, class
and all other C++ features are gone, and client code needs to use the new C
functions. As you said, it's not maintainable:(

In order to generate libpwiz.dll which can be connected to mzR directly, I
can imagine the following steps:
1. adds a C layer for ExtendedReader and uses the C function directly in
the Readers.cpp
2. compiles the reader part with MSVC, the generated dll code is compatible
with g++
3. compiles the msdata part using autotools, and get the pwiz library.

Regards,

-Han
