### ISSUE TITLE
Header for chromatograms

### ISSUE THREAD

**Issue by lgatto** [sneumann/mzR#74]
There is a need for a header function to extract feature data from the `chromatogramList`. I'll try to add it asap.

**Comment by jotsetung** [comment]
Related to https://github.com/sneumann/xcms/issues/125 I had a look at the https://github.com/wilsontom/sRm/ package. Seems to me that in that package the Q1 and Q3 mz are extracted from the ID of the chromatogram. Tried to figure out how this could be done with proteowizard, but failed because of the lack in documentation (at least to me the documentation is not really helpful).
