### ISSUE TITLE
mzR failes to install on Cent

### ISSUE THREAD

**Issue by Maddocent** [sneumann/mzR#78]

**Comment by sneumann** [comment]
Hi  Maddocent, we need a bit more information here. 
Which centos ? Wich error ? If you happen to have a docker container available, 
we can fix the compilation quicker. Usual reason is that instead of including 
the full 500MB boost source, we only have a subset, and that is not 
sufficient for your setup. Yours, Steffen

**Comment by Maddocent** [comment]
Sorry, I restarted my Rsession to clear the memory and than the installation ran smoothly. 
Thank you for the quick reply.
